// Content for popups in the interactive map.
var data = {
    "SlivenLandmarks": {
        "title": "Sliven Landmarks",
        "content": "Some of Sliven's landmarks are: Tuida Fortress, Halkata rock formation, Futula Cave, Futula Waterfall, Great fork peak, Blue stones (nature park).",
        "link1": { "href": "SlivenCulture", "label": "Culture" },
        "link2": { "href": "SlivenGeography", "label": "Geography" },
    },
    "SlivenCulture": {
        "title": "Sliven Culture",
        "content": "Sliven region includes settlements with rich cultural traditions, which have withstood the test of years and transferred to the present day. Spirituality in this part of Bulgaria has developed over the centuries thanks to the innate learning and freedom-loving spirit of the Bulgarians, his entrepreneurship in crafts and trade, as well as the good economic development of the region. People are from different ethnic groups, each with their own contribution to cultural and economic life.",
        "link1": { "href": "SlivenLandmarks", "label": "Landmarks" },
        "link2": { "href": "SlivenGeography", "label": "Geography" },
    },
    "SlivenGeography": {
        "title": "Sliven Geography",
        "content": "The territory of the district is characterized by varied relief. This determines the presence of two areas in terms of relief: in the north - semi-mountainous and mountainous, and in the south - flat. The southern part of the district includes part of the Tundzha hilly and low mountain area, Novozagorsko, Kermen and Sliven fields. The average altitude of the Sliven field is 150 m, and of the Kerm and Novozagorsk fields - about 130 m. The fertile fields located in the southern part of the district are surrounded on the north by the Balkan Mountains and the easternmost slopes of Sredna Gora. The highest peaks in the mountainous part are Chumerna (1536 m), Bulgarka (1181 m) and Razboyna (1128 m).",
        "link1": { "href": "SlivenLandmarks", "label": "Landmarks" },
        "link2": { "href": "SlivenCulture", "label": "Culture" },
    },
    "HaskovoLandmarks": {
        "title": "Haskovo Landmarks",
        "content": "Some of Haskovo's landmarks are: \"Asenova Fortress - Klokotnitsa\", \"Shishman's House\", \"Alexandrovska Tomb\", \"Sharapany area\", \"Stone mushrooms\", \"The stone wedding\"",
        "link1": { "href": "HaskovoCulture", "label": "Culture" },
        "link2": { "href": "HaskovoGeography", "label": "Geography" },
    },
    "HaskovoCulture": {
        "title": "Haskovo Culture",
        "content": "Haskovo region and one of the richest of historical and architectural sites according to data of the NKN declared and declared real cultural values number 597, of which 39 are of national importance. The area is extremely rich in real cultural values from prehistory and especially from the early Thracian era. Many megaliths are registered in the Straja-Sakar region and the Eastern Rhodopes, as well as many monumental stone Thracian tombs have been discovered in the area.",
        "link1": { "href": "HaskovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "HaskovoGeography", "label": "Geography" },
    },
    "HaskovoGeography": {
        "title": "Haskovo Geography",
        "content": "Haskovo Municipality is located in the hilly plains of southeastern Bulgaria and occupies the westernmost part of Haskovo region. It is strategically located between the Rhodopes and the Balkan Mountains. It is located not far from the borders with Turkey and Greece. The fastest and most direct road connecting Europe with Asia and the Middle East passes through the territory of Haskovo district. It is a curious fact that Haskovo is almost the same latitude as the village of Haskovo (Tashkent region, Uzbekistan), Rome (Italy), Barcelona (Catalonia, Spain), Tbilisi (Georgia) and Chicago (USA). Territory: 740.22 km². Settlements: 36 settlements: 1 town and 35 villages.",
        "link1": { "href": "HaskovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "HaskovoCulture", "label": "Culture" },
    },
    "StaraZagoraLandmarks": {
        "title": "Stara Zagora Landmarks",
        "content": "Some of Stara Zagora's landmarks are: \"Neolithic Dwellings Museum\", \"Lake Zagora\", \"St. Nicholas the Miracle Worker\", \"Saint Paisii Hilendarski\", \"Museum of Religions\", \"Regional History Museum\"",
        "link1": { "href": "Stara ZagoraCulture", "label": "Culture" },
        "link2": { "href": "Stara ZagoraGeography", "label": "Geography" },
    },
    "StaraZagoraCulture": {
        "title": "Stara Zagora Culture",
        "content": "In 1878, the famous architect from Austro-Hungary, Loubor Bayer, arrived in Stara Zagora, who designed the modern rectangular chess plan typical of today's Stara Zagora. On October 5, 1879, the General Governor of Eastern Rumelia Aleko Bogoridi laid the symbolic first stone for the restoration of the city. In Bulgaria, the only other city with such a development plan is Nova Zagora, which was also burned by the Turks. With chess planning are some of the most modern and large cities in the world.",
        "link1": { "href": "Stara ZagoraLandmarks", "label": "Landmarks" },
        "link2": { "href": "Stara ZagoraGeography", "label": "Geography" },
    },
    "StaraZagoraGeography": {
        "title": "Stara Zagora Geography",
        "content": "The town is located in the Stara Zagora plain - the eastern part of the Upper Thracian lowland - between Sarnena Sredna Gora, Svetiilii hills, Manastirski hills, Sakar mountain and Chirpan hills, near the river Bedechka with an average altitude of 196 m. It is located 209 km on an asphalt road and 250 km on a rail road from Sofia.",
        "link1": { "href": "Stara ZagoraLandmarks", "label": "Landmarks" },
        "link2": { "href": "Stara ZagoraCulture", "label": "Culture" },
    },
    "PazardzhikLandmarks": {
        "title": "Pazardzhik Landmarks",
        "content": "Some of Pazardzhik's landmarks are: Roman aqueduct, Peristera (fortress), Tsar Asen Mine, Scream Palace, Snezhanka Cave, Batak Dam",
        "link1": { "href": "PazardzhikCulture", "label": "Culture" },
        "link2": { "href": "PazardzhikGeography", "label": "Geography" },
    },
    "PazardzhikCulture": {
        "title": "Pazardzhik Culture",
        "content": "The city is home to one of the oldest theaters in the country, built with funds raised voluntarily by citizens. Today the theater is united with the puppet theater under the name Drama and Puppet Theater \"Konstantin Velichkov\".",
        "link1": { "href": "PazardzhikLandmarks", "label": "Landmarks" },
        "link2": { "href": "PazardzhikGeography", "label": "Geography" },
    },
    "PazardzhikGeography": {
        "title": "Pazardzhik Geography",
        "content": "Pazardzhik is located in the westernmost part of the Upper Thracian lowland, part of the common Pazardzhik-Plovdiv field, at an altitude of 205 m. Initially, the city was located on the left bank of the Maritsa. After his liberation from the Turkish yoke, he began to grow on the right bank of the river. Pazardzhik is a lowland town. The Pazardzhik field is surrounded by Sredna Gora, to the north and the Rhodopes, to the south.",
        "link1": { "href": "PazardzhikLandmarks", "label": "Landmarks" },
        "link2": { "href": "PazardzhikCulture", "label": "Culture" },
    },
    "PlovdivLandmarks": {
        "title": "Plovdiv Landmarks",
        "content": "Some of Plovdiv's landmarks are: Philippopolis Great Basilica, Ancient Theater Plovdiv, Clock Tower - Plovdiv, Eastern gate of Philippopolis, The sky is beating, Aqualand Aquapark - Plovdiv",
        "link1": { "href": "PlovdivCulture", "label": "Culture" },
        "link2": { "href": "PlovdivGeography", "label": "Geography" },
    },
    "PlovdivCulture": {
        "title": "Plovdiv Culture",
        "content": "There are many cultural, archeological and historical landmarks in Plovdiv and its surroundings, which provide conditions for the development of cultural tourism - Old Plovdiv, Assen Fortress, Bachkovo Monastery, Roman Fortress in Hissarya, Kalofer, Sopot, Karlovo and Klisura, Thracian cult center. in the village of Starosel, the Red Church near Perushtitsa, the fortress Anevsko Kale and others.",
        "link1": { "href": "PlovdivLandmarks", "label": "Landmarks" },
        "link2": { "href": "PlovdivGeography", "label": "Geography" },
    },
    "PlovdivGeography": {
        "title": "Plovdiv Geography",
        "content": "Plovdiv is located in the central part of the Upper Thracian lowland. The Maritsa River passes through it - the deepest river in Bulgaria. Thus, the city is naturally divided into two parts - north and south. To the north of Maritsa is located only the region \"North\", also known by its old name Karshiyaka, and to the south is the real part of the city, including the other five regions. It is 15 km north of the Rhodopes and 50 km south of the Balkan Mountains. The city is located 126 km from the capital Sofia, 381 km from Varna and 255 km from Bourgas.",
        "link1": { "href": "PlovdivLandmarks", "label": "Landmarks" },
        "link2": { "href": "PlovdivCulture", "label": "Culture" },
    },
    "SmolyanLandmarks": {
        "title": "Smolyan Landmarks",
        "content": "Some of Smolyan's landmarks are: \"The bride\", \"Capt. Quarter, Smolyan\", \"Mural (detail), Church St. вмцa. Nedelya, Raykovo district\", \"Ustovo quarter, Smolyan\", \"Rhodope Drama Theater Nikolai Haitov\", \"Stanevska mahala\"",
        "link1": { "href": "SmolyanCulture", "label": "Culture" },
        "link2": { "href": "SmolyanGeography", "label": "Geography" },
    },
    "SmolyanCulture": {
        "title": "Smolyan Culture",
        "content": "Smolyan is a center of significant cultural events - National Folklore Festival Rozhen, International Youth Folklore Orpheus Holidays, International Youth Hip-Hop Funk Festival Jam On It, International Plein Air on Painting, May Cultural Celebrations, the traditional holiday of mummers and masquerade games Pesponedelnik in the village of Shiroka Laka, international ethno-jazz festival July Jazz. October 21 is the holiday of Smolyan on the occasion of the Liberation of the Rhodopes from Ottoman rule during the Balkan War - 1912 and others. In the town of Smolyan in 1960 the Ensemble for Folk Songs and Dances Rodopa was established, which has an important role in preserving and promoting Rhodope folklore. He has been awarded a number of prestigious honors and awards for his work.",
        "link1": { "href": "SmolyanLandmarks", "label": "Landmarks" },
        "link2": { "href": "SmolyanGeography", "label": "Geography" },
    },
    "SmolyanGeography": {
        "title": "Smolyan Geography",
        "content": "The town of Smolyan is located in the central part of the Rhodopes, Southern Bulgaria. It is located 87 km west of Kardzhali, 96 km south of Plovdiv and 244 km from the capital Sofia. It occupies most of the valley of the Cherna River. On both banks of the river in the west-east direction are the three large districts - Smolyan, Raykovo and Ustovo.",
        "link1": { "href": "SmolyanLandmarks", "label": "Landmarks" },
        "link2": { "href": "SmolyanCulture", "label": "Culture" },
    },
    "KardzhaliLandmarks": {
        "title": "Kardzhali Landmarks",
        "content": "Some of Kardzhali's landmarks are: \"Perperikon\", \"The Thracian fortress\", \"Ustra Fortress\", \"Kardzhali Monastery\", \"The clock tower\", \"The water mirror\"",
        "link1": { "href": "KardzhaliCulture", "label": "Culture" },
        "link2": { "href": "KardzhaliGeography", "label": "Geography" },
    },
    "KardzhaliCulture": {
        "title": "Kardzhali Culture",
        "content": "Since 1999, Kardzhali has been a regional town. It is the largest administrative, industrial, commercial and cultural center of the Eastern Rhodopes. In 2012, on October 29, 2003, an impressive 6-meter monument to Vasil Levski with remarkable expressiveness and artistic value was unveiled on the central square of the city in front of the municipality. The author of the idea for the monument is Prof. Konstantin Denev. Five-ton stone blocks were used for the construction, which was completed in less than a month.",
        "link1": { "href": "KardzhaliLandmarks", "label": "Landmarks" },
        "link2": { "href": "KardzhaliGeography", "label": "Geography" },
    },
    "KardzhaliGeography": {
        "title": "Kardzhali Geography",
        "content": "Kardzhali is located in the heart of the Eastern Rhodope Mountains, on both banks of the Arda River. The nearest other regional town is Haskovo at a distance of approximately 50 km, and about 15 km from Kardzhali is the ancient rock town of Perperek (also called Perperikon), declared a monument of immovable cultural heritage of national importance since 1968, as follows : \"Kardzhali district.",
        "link1": { "href": "KardzhaliLandmarks", "label": "Landmarks" },
        "link2": { "href": "KardzhaliCulture", "label": "Culture" },
    },
    "SofiaLandmarks": {
        "title": "Sofia Landmarks",
        "content": "Some of Sofia's landmarks are: \"The dark hole.\", \"The seven thrones.\", \"Juglata\", \"Century-old oak forest in the Babin Plast area\", \"The water cave\", \"Sakaraja\"",
        "link1": { "href": "SofiaCulture", "label": "Culture" },
        "link2": { "href": "SofiaGeography", "label": "Geography" },
    },
    "SofiaCulture": {
        "title": "Sofia Culture",
        "content": "The Sofia is proud of its extremely rich cultural traditions and riches. Over the years, the folk customs, crafts and rituals of the region are passed on to future generations and preserved by many amateur groups and community centers. They find a field of expression in the wide range of events and festivals aimed at local folklore, which are organized annually in each of the municipalities.",
        "link1": { "href": "SofiaLandmarks", "label": "Landmarks" },
        "link2": { "href": "SofiaGeography", "label": "Geography" },
    },
    "SofiaGeography": {
        "title": "Sofia Geography",
        "content": "Sofia is located in western Bulgaria, in the Sofia valley, and is surrounded by mountains: Vitosha and Lozen to the south, Lyulin to the west and Stara Planina to the north. Its total area is 1344 km² and its average altitude is about 590 m. Several low-water rivers flow through it, the largest of which are Vladayska and Perlovska, which are tributaries of the Iskar River, which flows east of the city. The area is rich in mineral waters. Sofia has a temperate continental climate with an average annual temperature of about 10 ° C. The winter in the city is cold and snowy, and the summer is warm and sunny. The average annual rainfall is about 600 mm, reaching its maximum in May and June. In the flat part of the Sofia field chernozem resins, alluvial-meadow and deluvial-meadow soils predominate. The semi-mountainous regions are characterized by cinnamon and brown forest soils.",
        "link1": { "href": "SofiaLandmarks", "label": "Landmarks" },
        "link2": { "href": "SofiaCulture", "label": "Culture" },
    },
    "SofiaRegionLandmarks": {
        "title": "Sofia Region Landmarks",
        "content": "Some of Sofia Region's landmarks are: \"The dark hole.\", \"The seven thrones.\", \"Juglata\", \"Century-old oak forest in the Babin Plast area\", \"The water cave\", \"Sakaraja\"",
        "link1": { "href": "Sofia RegionCulture", "label": "Culture" },
        "link2": { "href": "Sofia RegionGeography", "label": "Geography" },
    },
    "SofiaRegionCulture": {
        "title": "Sofia Region Culture",
        "content": "The Sofia Region is proud of its extremely rich cultural traditions and riches. Over the years, the folk customs, crafts and rituals of the region are passed on to future generations and preserved by many amateur groups and community centers. They find a field of expression in the wide range of events and festivals aimed at local folklore, which are organized annually in each of the municipalities.",
        "link1": { "href": "Sofia RegionLandmarks", "label": "Landmarks" },
        "link2": { "href": "Sofia RegionGeography", "label": "Geography" },
    },
    "SofiaRegionGeography": {
        "title": "Sofia Region Geography",
        "content": "Sofia is located in western Bulgaria, in the Sofia valley, and is surrounded by mountains: Vitosha and Lozen to the south, Lyulin to the west and Stara Planina to the north. Its total area is 1344 km² and its average altitude is about 590 m. Several low-water rivers flow through it, the largest of which are Vladayska and Perlovska, which are tributaries of the Iskar River, which flows east of the city. The area is rich in mineral waters. Sofia has a temperate continental climate with an average annual temperature of about 10 ° C. The winter in the city is cold and snowy, and the summer is warm and sunny. The average annual rainfall is about 600 mm, reaching its maximum in May and June. In the flat part of the Sofia field chernozem resins, alluvial-meadow and deluvial-meadow soils predominate. The semi-mountainous regions are characterized by cinnamon and brown forest soils.",
        "link1": { "href": "Sofia RegionLandmarks", "label": "Landmarks" },
        "link2": { "href": "Sofia RegionCulture", "label": "Culture" },
    },
    "PernikLandmarks": {
        "title": "Pernik Landmarks",
        "content": "Some of Pernik's landmarks are: Churches in the Krakra fortress - Pernik, Krakra Fortress, Equestrian base Vitosha, Curved stone (peak), Rasnik Dam, Eco-trail Health Trail - Bankya",
        "link1": { "href": "PernikCulture", "label": "Culture" },
        "link2": { "href": "PernikGeography", "label": "Geography" },
    },
    "PernikCulture": {
        "title": "Pernik Culture",
        "content": "The largest documentary book depository and the main reference and information and local history center in the region is the Svetoslav Minkov Library. The fund of the library is about 292,000 library units. It was established in 1955 as a city public library. He started his activity with his transfer to the Palace of Culture in 1957. In 1983 she was awarded the Order of Cyril and Methodius I degree and named after the great Bulgarian writer Svetoslav Minkov. The library organizes exhibitions and literary meetings with publishers and authors. Since 2007, with Decree № 80 of April 7, 2006 of the Ministry of Culture, the library has changed its status from the UNB in ​​the Republic of Bulgaria and leaves the structure of the Municipal Complex \"Palace of Culture\".",
        "link1": { "href": "PernikLandmarks", "label": "Landmarks" },
        "link2": { "href": "PernikGeography", "label": "Geography" },
    },
    "PernikGeography": {
        "title": "Pernik Geography",
        "content": "Pernik is in the temperate-continental climate area, and only the Vitosha slope is in the mountainous climate area. Climatic conditions are determined by the relatively high average altitude - 750 m. A characteristic feature of the climate are the ground temperature inversions, especially during the winter months. Spring comes relatively late - in late March and early April. The average spring temperature is +9 ° C. For summer the average seasonal temperature is 19.9 ° C. The hottest month is July - average monthly temperature 29.6 ° C. The absolute maximum temperature is 38.1 ° C. Autumn is warmer than spring, the average seasonal temperature is 10 ° C. With westerly and southwesterly winds, which are prevalent, on the northern slopes of Golo Bardo, Fyon is observed, which is most typical in spring. The number of foggy days during the year is relatively large - 28.8 days. In the warm half of the year they are 2.5, and in the cold - 26.3 days.",
        "link1": { "href": "PernikLandmarks", "label": "Landmarks" },
        "link2": { "href": "PernikCulture", "label": "Culture" },
    },
    "GabrovoLandmarks": {
        "title": "Gabrovo Landmarks",
        "content": "Some of Gabrovo's landmarks are: \"Home of humor and satire\", \"Etar Ethnographic Open-Air Museum\", \"Monument to Vasil Aprilov\", \"Church St. Ivan Rilski\", \"Sokolski Monastery\",",
        "link1": { "href": "GabrovoCulture", "label": "Culture" },
        "link2": { "href": "GabrovoGeography", "label": "Geography" },
    },
    "GabrovoCulture": {
        "title": "Gabrovo Culture",
        "content": "The people of Gabrovo are known for their love of humor, for their annual humorous carnival of humor and satire, for their mechanical engineering, for their numerous monuments and bridges and long streets. At the end of the 12th century, crafts and trade developed here, as well as productions related to the maintenance and protection of the passes through the Balkans - blacksmithing, armaments, etc. During the Ottoman rule Gabrovo was a major craft and trade center. In the 19th century, 26 crafts were practiced here - blacksmithing, knife-making, chakra-making, pottery, braiding, leather-making, sericulture and much more.",
        "link1": { "href": "GabrovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "GabrovoGeography", "label": "Geography" },
    },
    "GabrovoGeography": {
        "title": "Gabrovo Geography",
        "content": "The town of Gabrovo is located at the foot of the Balkan Mountains, near the Shipka pass. It stretches along the Yantra River. The city is located 44 km from Veliko Tarnovo, 204 km from the capital Sofia, 137 km from Plovdiv, 263 km from Varna and 247 km from Bourgas. Gabrovo is connected to the railway transport in Bulgaria by the line Gabrovo-Tsareva Livada. Gabrovo is one of the most important road connections crossing Bulgaria in the north-south direction, which is part of the Pan-European Transport Corridor IX (Helsinki - St. Petersburg - Kyiv - Bucharest - Ruse - Veliko Tarnovo - Gabrovo - Stara Zagora - Dimitrovgrad with deviations to Greece and Turkey).",
        "link1": { "href": "GabrovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "GabrovoCulture", "label": "Culture" },
    },
    "LovechLandmarks": {
        "title": "Lovech Landmarks",
        "content": "Some of Lovech's landmarks are: Covered bridge Lovech, Lovech Zoo, Lovech fortress, Hisar Fortress, Watch the bridge, White Anasta's Fountain",
        "link1": { "href": "LovechCulture", "label": "Culture" },
        "link2": { "href": "LovechGeography", "label": "Geography" },
    },
    "LovechCulture": {
        "title": "Lovech Culture",
        "content": "Cultural development is based on the activities of the Nativity of the Virgin Monastery. His most famous manuscripts are Trebnik (preserved in the Rila Monastery) and the transcript of the Synod of Boril (preserved in St. Petersburg). On January 1, 1870 the Lovchani Chitalishte \"Nauka\" was founded. A library was arranged next to it, fairy tales, parties, Sunday readings were performed, and in the same year the first theatrical play \"Raina Knyaginya\" was performed.",
        "link1": { "href": "LovechLandmarks", "label": "Landmarks" },
        "link2": { "href": "LovechGeography", "label": "Geography" },
    },
    "LovechGeography": {
        "title": "Lovech Geography",
        "content": "Lovech is located on the border of the Danube hilly plain and the foothills of Stara Planina. 158 km to the west is Sofia, 159 km to the south is Plovdiv, 306 km to the northeast is Varna, 300 km to the southeast is Burgas, 30 km to the south is Troyan, 30 km to the north is Pleven and 30 km to the north is Pleven. km to the east is Sevlievo. It is located on both sides of the Osam River, which, coming out of a rocky gorge, makes several curves between the hills \"Stratesh\", \"Hisarya\" and \"Bash Bunar\".The relief of the surroundings is hilly and strongly rugged.To the east is the rock crown of Stratesh Hill.The northwestern part of the city gradually descends to the plain relief of the neighboring municipality of Pleven.The average altitude of Lovech is 360 m.The highest point in the city is the hill\"Ak Bair\", located in the southeast with its 450 m above sea level, and the central part of Lovech is the lowest point with 150 - 190 m above sea level and a slope of 3-8%.",
        "link1": { "href": "LovechLandmarks", "label": "Landmarks" },
        "link2": { "href": "LovechCulture", "label": "Culture" },
    },
    "PlevenLandmarks": {
        "title": "Pleven Landmarks",
        "content": "Some of Pleven's landmarks are Kaylaka Zoo, Storgozia Fortress, Totlebenov Val Dam, Chernelka Eco-trail, Riben Horse Base, The Greenhouses Cave",
        "link1": { "href": "PlevenCulture", "label": "Culture" },
        "link2": { "href": "PlevenGeography", "label": "Geography" },
    },
    "PlevenCulture": {
        "title": "Pleven Culture",
        "content": "At the same distance from the Balkan Mountains and the Danube, in the heart of the Danube plain is the city of Pleven. It is located in a small syncline valley, also called Kailashka Valley, formed by the Tuchenitsa River and its tributaries Grivishka and Chaira. Pleven is 170 km northeast of Sofia and with a population of 106 thousand people is the seventh largest in Bulgaria.",
        "link1": { "href": "PlevenLandmarks", "label": "Landmarks" },
        "link2": { "href": "PlevenGeography", "label": "Geography" },
    },
    "PlevenGeography": {
        "title": "Pleven Geography",
        "content": "The city of Pleven is located in the central part of Moesia, at the western foot of the Pleven Heights, the Middle Danube Plain. The city is almost equidistant from the Danube and Stara Planina rivers, with good land connections with Sofia (160 km), Varna (300 km), Ruse (150 km), Lovech (30 km), as well as with the lands north of the Danube and other smaller settlements in the region. The main city-forming factor in antiquity was the fertile overflow valley of the Tuchenitsa River (Tuchenishka or Plevenska Bara). The relief in this part of the Danube plain and the good road connections facilitate the construction and development of the initially scattered small settlements as an important road junction and a center with good indicators of economic progress of Ancient Thrace, the Roman Empire and Bulgaria.",
        "link1": { "href": "PlevenLandmarks", "label": "Landmarks" },
        "link2": { "href": "PlevenCulture", "label": "Culture" },
    },
    "VelikoTarnovoLandmarks": {
        "title": "Veliko Tarnovo Landmarks",
        "content": "Some of Veliko Tarnovo's landmarks are: The Monkey House, Stambolov Bridge, Kartal Waterfall, Baira Fortress, The Baldwin Tower",
        "link1": { "href": "Veliko TarnovoCulture", "label": "Culture" },
        "link2": { "href": "Veliko TarnovoGeography", "label": "Geography" },
    },
    "VelikoTarnovoCulture": {
        "title": "Veliko Tarnovo Culture",
        "content": "In the region of Veliko Tarnovo, there are hundreds of architectural and cultural monuments from Antiquity, the Middle Ages, the Renaissance and Modernism. The city was a direct successor of the Old Bulgarian culture during its capital period. The golden culture of Pliska and Preslav is developing in the town. The dynasties of the Second Bulgarian State also left their mark on the cultural image and upgraded the Bulgarian culture. During the Ottoman rule, the city was strongly influenced by the Orient. The Orthodox part of the population was influenced by Byzantine-Greek culture. Folklore motifs in music and dance have been preserved over the centuries.",
        "link1": { "href": "Veliko TarnovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "Veliko TarnovoGeography", "label": "Geography" },
    },
    "VelikoTarnovoGeography": {
        "title": "Veliko Tarnovo Geography",
        "content": "The relief of the municipality of Veliko Tarnovo is diverse - plain-hilly and mountainous. Veliko Tarnovo is located at an average altitude of 208 m on the slopes of beautiful gorges and meanders of the Yantra River. The city is naturally protected by the river and the rocky crowns that surround it. The hills on which the city of Veliko Tarnovo is located have a limestone composition with a layer of sand, clay and gray marl, accumulated as sediment from the Cretaceous sea, which flooded our lands millions of years ago. The rock wreath around the city was declared the National Arboretum \"Second Bulgarian State\" in 1981.",
        "link1": { "href": "Veliko TarnovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "Veliko TarnovoCulture", "label": "Culture" },
    },
    "MontanaLandmarks": {
        "title": "Montana Landmarks",
        "content": "Some of Montana's landmarks are: Castro Fortress of Montanesium, Ink Dam, Bergland Horse Base, Marble cave - Berkovitsa, Momin kamik, Chiprovtsi Monastery St. Ivan Rilski",
        "link1": { "href": "MontanaCulture", "label": "Culture" },
        "link2": { "href": "MontanaGeography", "label": "Geography" },
    },
    "MontanaCulture": {
        "title": "Montana Culture",
        "content": "The history of the Montana region is centuries old and dates back to ancient times. In antiquity the region was inhabited by the Thracian tribe \"Tribali\". After becoming part of the Eastern Roman Empire, the settlements of Montanensium / Montana /, Almus / Lom / and Medeca / Varshets / appeared in the area, later Slavs and Bulgarians came. The modern culture of the region has preserved the strong influence of different eras, but deep in its essence it is Bulgarian, European and universal in spirit.",
        "link1": { "href": "MontanaLandmarks", "label": "Landmarks" },
        "link2": { "href": "MontanaGeography", "label": "Geography" },
    },
    "MontanaGeography": {
        "title": "Montana Geography",
        "content": "Montana is bordered on the north by the Canadian provinces of British Columbia, Alberta and Saskatchewan, on the east by the states of North Dakota and South Dakota, on the south by Wyoming, and on the west by Idaho. The total area of ​​the state is 381,156 km, of which 377,295 km are on land (according to this indicator, Montana ranks fourth in the country after Alaska, Texas and California and is also the largest landlocked state in the United States). The western part of the state is mountainous, geographically it is the northern part of the Rocky Mountains. The eastern part (about 60%) is the northern part of the Great Plains and is covered with prairies. However, even to the east of the Rockies there are small isolated ridges that cut through the plains. Through the territory of Montana passes the American continental watershed, which separates the basins of the Pacific and Atlantic Oceans. The highest point is Granite Peak (3901 m).",
        "link1": { "href": "MontanaLandmarks", "label": "Landmarks" },
        "link2": { "href": "MontanaCulture", "label": "Culture" },
    },
    "VratcaLandmarks": {
        "title": "Vratca Landmarks",
        "content": "Some of Vratca's landmarks are: Mogila mound, The tower of the townspeople, Vrachanska Skaklya (waterfall), Nursery Dam, Glacier (cave), The gate (passage),Shopkata Waterfall ",
        "link1": { "href": "VratcaCulture", "label": "Culture" },
        "link2": { "href": "VratcaGeography", "label": "Geography" },
    },
    "VratcaCulture": {
        "title": "Vratca Culture",
        "content": "There are many cultural monuments on the territory of the district, such as \"Gradishteto\" - remains of a prehistoric settlement located 3 km northwest of the center of Krivodol, ancient mausoleum in \"Rosnenitsa\" - Urovene - II-IV c. ., \"The Humpback Bridge\" near the village of Lipnitsa and many others.In the town of Vratsa you can visit the towers of Meshchiite and Kurtpashov, built in the XVII century, as housing and defense. The towers have great historical and architectural value and have been declared cultural monuments of national importance.",
        "link1": { "href": "VratcaLandmarks", "label": "Landmarks" },
        "link2": { "href": "VratcaGeography", "label": "Geography" },
    },
    "VratcaGeography": {
        "title": "Vratca Geography",
        "content": "The town of Vratsa is located at the foot of the Vratsa Mountain. Vratsa is the starting point to the gorge Vratsata and the Ledenika cave. The city is located 370 m above sea level. The northernmost residential and industrial districts of the city are at 340 m above sea level, while the southernmost, along the Leva, are at 400 m above sea level. Vratsa has beautiful surroundings. To the south are the gray-violet rocks of the Vratsa Mountains, to the north, above the low stone plateau with soft and rounded surface forms, Milin Kamak rises, and to the east the low peaks of the Veslets hill alternate.",
        "link1": { "href": "VratcaLandmarks", "label": "Landmarks" },
        "link2": { "href": "VratcaCulture", "label": "Culture" },
    },
    "KyustendilLandmarks": {
        "title": "Kyustendil Landmarks",
        "content": "Some of Kyustendil's landmarks are: Hisarlaka (fortress), Kyustendil Zoo, Hisarlaka (forest park), Shegava Canyon, Kadin Bridge, Polska Skakavitsa waterfall",
        "link1": { "href": "KyustendilCulture", "label": "Culture" },
        "link2": { "href": "KyustendilGeography", "label": "Geography" },
    },
    "KyustendilCulture": {
        "title": "Kyustendil Culture",
        "content": "The history of Kyustendil as an urban settlement is nearly two thousand years old and eight thousand years of settlement life in years. Kyustendil is one of the most ancient cities in the Bulgarian lands and has an incredibly significant and rich history.",
        "link1": { "href": "KyustendilLandmarks", "label": "Landmarks" },
        "link2": { "href": "KyustendilGeography", "label": "Geography" },
    },
    "KyustendilGeography": {
        "title": "Kyustendil Geography",
        "content": "Kyustendil is located in the southern part of the Kyustendil valley, at the foot of the Osogovo mountain, at 527 meters above sea level, on both banks of the river Banshtitsa, a right tributary of the river Struma. South of the town rises the hill \"Hisarlaka\" - northeastern branch of Osogovo. The distance from Kyustendil to the capital Sofia is 103 km, to Plovdiv is 259 km, to Varna is 547 km, to Bourgas is 498 km, to the border with Northern Macedonia is 22 km, to the border with Serbia - about 30 km. The city is an important road junction on the road Sofia - Skopje and the railway station on the line Sofia - Pernik - Gueshevo. Pan-European Transport Corridor 8 (Vlora - Tirana - Skopje - Sofia - Burgas - Asia) passes through Kyustendil.",
        "link1": { "href": "KyustendilLandmarks", "label": "Landmarks" },
        "link2": { "href": "KyustendilCulture", "label": "Culture" },
    },
    "VidinLandmarks": {
        "title": "Vidin Landmarks",
        "content": "Some of Vidin's landmarks are: \"Baba Vida Fortress\", \"Historical Museum Konaka - Vidin\", \"Cathedral St. Dimitar Solunski - Vidin\", \"Monument to the Sorrowful Warrior. \", \"Mosque with a library of Osman Pazvantoglu\", \"Mustafa Pasha Mosque\"",
        "link1": { "href": "VidinCulture", "label": "Culture" },
        "link2": { "href": "VidinGeography", "label": "Geography" },
    },
    "VidinCulture": {
        "title": "Vidin Culture",
        "content": "The geographical location of the municipality of Vidin, the existing natural resources, the rich cultural and historical heritage and the diverse cultural calendar are prerequisites for the development of tourism.",
        "link1": { "href": "VidinLandmarks", "label": "Landmarks" },
        "link2": { "href": "VidinGeography", "label": "Geography" },
    },
    "VidinGeography": {
        "title": "Vidin Geography",
        "content": "The city is located on the right bank of the Danube, which is the Romanian islands of Small Calafat and Golyam Calafat and the Bulgarian islands of Kutovo (or Golia Ostrov), Big Twin and Small Twin. Opposite Vidin is the town of Calafat, Romania. Vidin is located 58 km from Lom, 87 km from Montana, 125 km from Vratsa, 197 km from the capital Sofia, 362 km from Plovdiv, 508 km from Varna and 600 km from Bourgas.",
        "link1": { "href": "VidinLandmarks", "label": "Landmarks" },
        "link2": { "href": "VidinCulture", "label": "Culture" },
    },
    "BurgasLandmarks": {
        "title": "Burgas Landmarks",
        "content": "Some of Burgas's landmarks are: Poda Burgas (area), Foros (fortress), St. Anastasia Island, Ruskina Dupka Cave, Mesemvria (fortress), Archaeological Museum - Nessebar, Snake Island (St. Thomas)",
        "link1": { "href": "BurgasCulture", "label": "Culture" },
        "link2": { "href": "BurgasGeography", "label": "Geography" },
    },
    "BurgasCulture": {
        "title": "Burgas Culture",
        "content": "Burgas region as a crossroads of nations and cultures has a centuries-old history. Architectural and archeological relics from Thracian times (Pomorie tomb), from Roman Byzantine times (fortification walls and Roman baths), unique historical monuments can be seen on the territory of the district. Another group of anthropological resources for tourism are religious sites - churches and monasteries. Tourists can witness unique traditions and ritual dances, preserved to this day in the villages of Strandzha Mountain. Firefighting is a unique phenomenon, full of mysticism, which to this day has not revealed its mysteries.",
        "link1": { "href": "BurgasLandmarks", "label": "Landmarks" },
        "link2": { "href": "BurgasGeography", "label": "Geography" },
    },
    "BurgasGeography": {
        "title": "Burgas Geography",
        "content": "The city is located in the eastern part of the Burgas lowland, which is located east of the Upper Thracian lowland. Located in the westernmost point of the Black Sea, Bourgas gives the name of the bay of the same name, which is the largest and most prominent in the continent of the Bulgarian Black Sea coast. The town is surrounded by the lakes Burgas, Atanasovsko and Mandrensko to the west, northeast and southwest, and east of the Black Sea. Between the Burgas and Mandre lakes, at a height of 209 m, rises the peak of Varli Bryag. It is also the highest point of Burgas. There are two sandy slopes in Burgas: Kumluka, located between Lake Burgas and the Black Sea, which is about 3 km long and about 1 km wide; and Atanasovska kosa, located between Atanasovsko Lake and the Black Sea and about 1 km long. In the waters of the Burgas Bay is the Black Sea island of St. Anastasia, which is also part of the city. It is 6.5 km from the coast and is built of volcanic rocks. At its highest point it is 12 m high and its area is 22 decares.",
        "link1": { "href": "BurgasLandmarks", "label": "Landmarks" },
        "link2": { "href": "BurgasCulture", "label": "Culture" },
    },
    "YambolLandmarks": {
        "title": "Yambol Landmarks",
        "content": "Some of Yambol's landmarks are: \"Reaper Monument\", \"Kabile\", \"Kaloyanovsky Thracian Tomb\", \"Karandila\", \"Futula Cave\", \"Rakovski's Cave\"",
        "link1": { "href": "YambolCulture", "label": "Culture" },
        "link2": { "href": "YambolGeography", "label": "Geography" },
    },
    "YambolCulture": {
        "title": "Yambol Culture",
        "content": "The history of the town of Yambol began even before the creation of the Bulgarian state. In 293, Emperor Diocletian embarked on a journey on these lands. At the beginning of May he was in Adrianopol, from where he went to Augusta Trayana, Philippopolis and Serdika. The emperor's path passed right through the place where Yambol is now located and where there was probably some small settlement. The Emperor was amazed by the fertile lands, the beautiful nature, the good living conditions and decided that there should be a city in this place. And it is not any, but a big and beautiful city with the divine name Diospolis, a city of Zeus.",
        "link1": { "href": "YambolLandmarks", "label": "Landmarks" },
        "link2": { "href": "YambolGeography", "label": "Geography" },
    },
    "YambolGeography": {
        "title": "Yambol Geography",
        "content": "The town of Yambol is located in southeastern Bulgaria and is located on both banks of the Tundzha River. It is located 77 km from the Black Sea and south of the Thrace highway. The distance to the capital Sofia is 297 km, to Plovdiv is 168 km, to Varna is 216 km and the distance to Bourgas is 92 km. On the land of the town is the protected area \"Ormana\", which has rare species of native plants and local small game, as well as a farm for breeding under artificial conditions of Colchis pheasant. The Ormana long forest has rare species of local plants and local small game, diverse flora and fauna - snowdrop, frost and Colchis pheasant. The area is a favorite place for recreation of Yambol residents on their weekends.",
        "link1": { "href": "YambolLandmarks", "label": "Landmarks" },
        "link2": { "href": "YambolCulture", "label": "Culture" },
    },
    "RazgradLandmarks": {
        "title": "Razgrad Landmarks",
        "content": "Some of Razgrad's landmarks are: Razgrad Zoo, Abritus (archeological reserve), Beli Lom Dam, Gagovo tomb, Demir baba teke, Omurtag's grave.",
        "link1": { "href": "RazgradCulture", "label": "Culture" },
        "link2": { "href": "RazgradGeography", "label": "Geography" },
    },
    "RazgradCulture": {
        "title": "Razgrad Culture",
        "content": "Razgrad is the successor of the Roman Abritus (its ruins are near the city), which originated on the site of a Thracian settlement of unknown name. The medieval Bulgarian settlement of Hrazgrad (Hrisgrad) appeared on the remains of the Byzantine city destroyed by the invasions.            In 1388 it fell under Turkish rule.Since 1573 Razgrad has been a waqf settlement and gradually became a craft center.Silkworms were also raised.It has had a trading colony from Dubrovnik since the 16 th century.",
        "link1": { "href": "RazgradLandmarks", "label": "Landmarks" },
        "link2": { "href": "RazgradGeography", "label": "Geography" },
    },
    "RazgradGeography": {
        "title": "Razgrad Geography",
        "content": "The town of Razgrad is located in the valley of the Beli Lom River, in the historical and geographical region of Ludogorie. It is located 65 km southeast of Ruse, 35 km north of Targovishte, 50 km northwest of Shumen, 130 km northwest of Varna. The international European road E70 connects it with the nearby port cities of Ruse and Varna. About 7 km from the town of Razgrad is located the railway line Ruse - Varna.",
        "link1": { "href": "RazgradLandmarks", "label": "Landmarks" },
        "link2": { "href": "RazgradCulture", "label": "Culture" },
    },
    "TargovishteLandmarks": {
        "title": "Targovishte Landmarks",
        "content": "Some of Targovishte's landmarks are: \"Monument to the unknown warrior - Targovishte\", \"Church of St. Ivan Rilski - Targovishte\", \"Ministries - Targovishte\", \"Regional History Museum - Targovishte\", \"Church of the Assumption of the Virgin Mary - Targovishte\", \"Art Gallery Nikola Marinov - Targovishte\"",
        "link1": { "href": "TargovishteCulture", "label": "Culture" },
        "link2": { "href": "TargovishteGeography", "label": "Geography" },
    },
    "TargovishteCulture": {
        "title": "Targovishte Culture",
        "content": "Targovishte district is an authoritative and active cultural center. Targovishte hosts traditional national events, including in the European palette. There are holidays of the women's and girls' choirs, theatre festival Days of the big theater in the small town, international festival of professional performances for children The Magic Curtain. In the town of Popovo is held once every two years.",
        "link1": { "href": "TargovishteLandmarks", "label": "Landmarks" },
        "link2": { "href": "TargovishteGeography", "label": "Geography" },
    },
    "TargovishteGeography": {
        "title": "Targovishte Geography",
        "content": "The town is located in the Danube plain, about 170 m above sea level, north of the Preslav Mountains. It is located 339 km northeast of Sofia, 41 km west of Shumen, 25 km northwest of Veliki Preslav and 100 km northeast of Veliko Tarnovo. The proximity of the city to the starting points of the country Varna (110 km) and Ruse (100 km), as well as major economic centers such as Shumen, Tarnovo and Ruse makes it a natural strategic crossroads. The medium-high relief helps the development of both agriculture and industrial production.",
        "link1": { "href": "TargovishteLandmarks", "label": "Landmarks" },
        "link2": { "href": "TargovishteCulture", "label": "Culture" },
    },
    "ShumenLandmarks": {
        "title": "Shumen Landmarks",
        "content": "Some of Shumen's landmarks are: \"Osmar's eye\", \"Madara Horseman\", \"Pliska\", \"Ovech Fortress\", \"Svecarska Tomb\", \"Zheravna Reserve\"",
        "link1": { "href": "ShumenCulture", "label": "Culture" },
        "link2": { "href": "ShumenGeography", "label": "Geography" },
    },
    "ShumenCulture": {
        "title": "Shumen Culture",
        "content": "Shumen Region has a rich cultural and historical heritage. The first traces date back to the early period of the Old Stone Age, follow the stone-copper and bronze. In 681, the First Bulgarian State was founded here. Here are located the ancient Bulgarian capitals Pliska and Veliki Preslav.",
        "link1": { "href": "ShumenLandmarks", "label": "Landmarks" },
        "link2": { "href": "ShumenGeography", "label": "Geography" },
    },
    "ShumenGeography": {
        "title": "Shumen Geography",
        "content": "Shumen is located in the Shumen field, which is open to the southeast and gradually decreases in height; the western parts of the city lie about 280-300 m above sea level, and the easternmost - 180-200 m. The city is located at the foot of the Shumen plateau, which has a very diverse nature. Its ridge rises to 500 m above sea level. Its elevation in relation to the city is about 250 - 300 m. The small river Poroyna passes through Shumen. 3 km west of the modern town, on a part of the Shumen plateau, is the area of Hisarlaka (or the Old Town), surrounded by steep valleys, where streams flow all year round.",
        "link1": { "href": "ShumenLandmarks", "label": "Landmarks" },
        "link2": { "href": "ShumenCulture", "label": "Culture" },
    },
    "DobrichLandmarks": {
        "title": "Dobrich Landmarks",
        "content": "Some of Dobrich's landmarks are: Botevo Dam, Chiflika Chukurovo (ethnographic complex), Equestrian base Borisovi, Rock Monastery Raklenata Cave - Balik village, Tarapanata Rock Monastery - Balik village, Kranei Fortress",
        "link1": { "href": "DobrichCulture", "label": "Culture" },
        "link2": { "href": "DobrichGeography", "label": "Geography" },
    },
    "DobrichCulture": {
        "title": "Dobrich Culture",
        "content": "In the region of Dobrich district there are museums and museum collections in every municipal center, and in the district city the institution has the status of a Regional History Museum. Apart from the Art Gallery - Dobrich, exhibitions of works by Bulgarian and foreign artists are exhibited in other municipal centers. Dora Gabe Regional Library is active in the field, which provides methodological assistance to all smaller libraries located in local community centers. They have been a specific feature of Bulgaria since the 19th century and are unique centers for cultural and educational activities. They operate in almost every settlement, regardless of its size, preserving and developing Bulgarian traditions and spirit. There are separate groups for authentic folklore, theater troupes for children and adults, learning arts and crafts, musical instruments, song and dance.",
        "link1": { "href": "DobrichLandmarks", "label": "Landmarks" },
        "link2": { "href": "DobrichGeography", "label": "Geography" },
    },
    "DobrichGeography": {
        "title": "Dobrich Geography",
        "content": "The town of Dobrich is located in the Danube plain   on the Dobrudzha plateau. The city is an independent municipality and the administrative center of the district of the same name. The territory of the municipality has a total area of ​​1705 hectares. It is located on both banks of the small Dobrich River (Suha Reka) at 220 m above sea level. The city is located 477 km from the capital Sofia, 405 km from Plovdiv, 164 km from Bourgas, 208 km from Ruse, 51 km northwest of Varna, 89 km southeast of Silistra and 33 km southwest of Balchik. The city is preferred by many people because of its good location (about 30 km from the Black Sea). It is also famous for the city park \"St. George\", which is one of the largest city parks in Bulgaria and in some places it has a completely pristine nature.",
        "link1": { "href": "DobrichLandmarks", "label": "Landmarks" },
        "link2": { "href": "DobrichCulture", "label": "Culture" },
    },
    "VarnaLandmarks": {
        "title": "Varna Landmarks",
        "content": "Some of Varna's landmarks are: Dolphinarium - Varna, Varna Aquarium (museum), Planetarium - Varna, Naval Museum - Varna, Varna Zoo, Varna necropolis, Phanagoria (proto-Bulgarian settlement - museum)",
        "link1": { "href": "VarnaCulture", "label": "Culture" },
        "link2": { "href": "VarnaGeography", "label": "Geography" },
    },
    "VarnaCulture": {
        "title": "Varna Culture",
        "content": "The city of Varna is an important cultural center with a full range of activities in the field of culture - theater, museums, film activities, library, fine arts, complex community center activities. The museum activity is of suburban importance. It is represented by various types of museum sites, among which the specialized ones predominate: Regional History Museum, Naval Museum, Archaeological Museum, Archaeological Museum, Natural Science Museum, Puppet Museum, Museum of Modern History of Varna, Park Museum \"Vladislav Varnenchi\". Apart from being sites with cultural functions, museums are also an important tourist resource.",
        "link1": { "href": "VarnaLandmarks", "label": "Landmarks" },
        "link2": { "href": "VarnaGeography", "label": "Geography" },
    },
    "VarnaGeography": {
        "title": "Varna Geography",
        "content": "The city of Varna is located in the Varna lowlands, on the shores of Varna Bay and between Varna Lake and the Frangen Plateau. Part of the city is located south of the Varna lake and connects with its central parts through the Asparuhov Bridge. Varna covers an area of ​​238 km². The city is located 441 km from the capital Sofia, 388 km from Plovdiv and 130 km from Bourgas. The nearest regional town is Dobrich, which is located 52 km. South of the strait connecting the bay and the lake are the Asparuhovo and Galata neighborhoods. On the north coast are the industrial zone and the port complex. Northeast of them are the central part of the city with the historic center (the so-called \"Greek Quarter\") and the central beaches.",
        "link1": { "href": "VarnaLandmarks", "label": "Landmarks" },
        "link2": { "href": "VarnaCulture", "label": "Culture" },
    },
    "SilistraLandmarks": {
        "title": "Silistra Landmarks",
        "content": "Some of Silistra's landmarks are: \”Durostorum Fortress\", \”Mejidi Tabia Fortress\", \”Art Gallery\", \”The Srebarna Reserve\", \”Danube Garden\", \”Mejidi Tabia Fortress\"",
        "link1": { "href": "SilistraCulture", "label": "Culture" },
        "link2": { "href": "SilistraGeography", "label": "Geography" },
    },
    "SilistraCulture": {
        "title": "Silistra Culture",
        "content": "It is believed that the city was founded by the Thracians. Then the Roman Empire conquered the city and founded the ancient Durostorum in 106, when on the orders of Emperor Trajan on the territory of today's city is housed one of the elite Roman military units - XI Claudius Legion. This is the beginning of a remarkable and glorious story. In 169, the philosopher Emperor Marcus Aurelius declared Durostorum a self-governing Roman city - municipality. Between the 2nd and 6th centuries, Durostorum was the empire's main outpost against the barbarians. Here was born the savior of Rome, also called the last Roman Flavius Aetius. Here, in 303-307, 12 saints died martyrdom, becoming the foundation of Christianity in the Bulgarian lands.",
        "link1": { "href": "SilistraLandmarks", "label": "Landmarks" },
        "link2": { "href": "SilistraGeography", "label": "Geography" },
    },
    "SilistraGeography": {
        "title": "Silistra Geography",
        "content": "The city is located in northeastern Bulgaria, ie. in South Dobrudja. It is located 433 km from the Bulgarian capital Sofia, 124 km from Ruse, 116 km from Razgrad, 112 km from Shumen, 90 km from Dobrich, 15 km from Calarasi, 148 km from Constanţa and 127 km from the Romanian capital Bucharest. The Pan - European Transport Corridor 7 passes through it.",
        "link1": { "href": "SilistraLandmarks", "label": "Landmarks" },
        "link2": { "href": "SilistraCulture", "label": "Culture" },
    },
    "RuseLandmarks": {
        "title": "Ruse Landmarks",
        "content": "Some of Ruse's landmarks are: \"The Monument of Freedom\", \"The profitable building\", \"Alexandrovska Street\", \"Girdap Joint-Stock Savings Company (The Clock)\", \"The Simeon Brothers' Bank.\", \"Holy Trinity Church\"",
        "link1": { "href": "RuseCulture", "label": "Culture" },
        "link2": { "href": "RuseGeography", "label": "Geography" },
    },
    "RuseCulture": {
        "title": "Ruse Culture",
        "content": "Ruse is one of the cities in Bulgaria that attracts both with its magnificent architecture and its rich historical past. Ruse is the hometown of a number of Bulgarian Revivalists, guardians of the Bulgarian spirit, revolutionaries and participants in the Liberation. At the same time, however, it is a cosmopolitan for its time, tolerating different religions and embracing technological and social innovations European city. After the Liberation, the city was the most populous, but also the most modern city in the Principality of Bulgaria, before the new capital surpassed it in population. Many of the technological innovations from the end of the 19th and the beginning of the 20th century found their first application in the beautiful Danube city.",
        "link1": { "href": "RuseLandmarks", "label": "Landmarks" },
        "link2": { "href": "RuseGeography", "label": "Geography" },
    },
    "RuseGeography": {
        "title": "Ruse Geography",
        "content": "Ruse is located in the western part of the largest Danube lowland - the Coast, and northeast of the mouth of the river Rusenski Lom. While the northern bank of the Danube (on the Romanian side) is low and swampy, the southern bank near Ruse is high and dry. There are two flood terraces and three floodplain terraces - 15 - 22 m, 30 - 66 m and 54 - 65 m. The average altitude of the city is 45.5 m. The city is located 309 km from the capital Sofia, 312 km from Plovdiv, 193 km from Varna and 240 km from Bourgas. The built-up part of Ruse has the shape of an ellipse along the river with a total length of about 11 km. The city covers the area between the landlocked island of Matei and the mouth of Rusenski Lom from west to the height of the Sickle (because it surrounds the city of Ruse from the south, like a sickle).",
        "link1": { "href": "RuseLandmarks", "label": "Landmarks" },
        "link2": { "href": "RuseCulture", "label": "Culture" },
    },
    "BlagoevgradLandmarks": {
        "title": "Blagoevgrad Landmarks",
        "content": "Some of Blagoevgrad's landmarks are Blagoevgrad Zoo, Horse base Fortuna, Tserovo Fortress, The Stob pyramids, Boychova Dupka Cave, Bohemia Waterfalls, Devil's Waters Waterfalls, Tsarev Vrah (megalithic sanctuary), Medieval monastery - Tsarvaritsa, Kalin Peak, The Black Lake",
        "link1": { "href": "BlagoevgradCulture", "label": "Culture" },
        "link2": { "href": "BlagoevgradGeography", "label": "Geography" },
    },
    "BlagoevgradCulture": {
        "title": "Blagoevgrad Culture",
        "content": "The administrative center of the district is the town of Blagoevgrad. With the Southwestern University \"Neofit Rilski\", AUBG, numerous educational institutions and cultural institutes, the city is a center of youth in Bulgaria, the Balkans and Europe and is established as a cultural center not only in the district but also nationally. Here he develops creative activity and the world-famous ensemble for folk songs and dances \"Pirin\", which has won countless fans of Bulgarian music and dance.",
        "link1": { "href": "BlagoevgradLandmarks", "label": "Landmarks" },
        "link2": { "href": "BlagoevgradGeography", "label": "Geography" },
    },
    "BlagoevgradGeography": {
        "title": "Blagoevgrad Geography",
        "content": "Blagoevgrad is located in the valley of the Struma and the smaller river Bistritsa flows through it. It is located at 360 m above sea level in the Blagoevgrad valley between the Rila and Vlahina mountains and is close to the Pirin mountain. Blagoevgrad is located 102 km from the capital Sofia, 237 km from Plovdiv, 545 km from Varna and 476 km from Bourgas. Blagoevgrad is characterized by mostly mountainous and valley relief, as the groundwater is fed by Bistritsa. Blagoevgrad is among the cities with the most sunny days a year. [3] The climate is transitional-continental due to the air masses that penetrate from the south along the valley of the river Struma.",
        "link1": { "href": "BlagoevgradLandmarks", "label": "Landmarks" },
        "link2": { "href": "BlagoevgradCulture", "label": "Culture" },
    },
};