var data = {
    "SlivenLandmarks": {
        "title": "Sliven Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SlivenCulture", "label": "Culture" },
        "link2": { "href": "SlivenGeography", "label": "Geography" },
    },
    "SlivenCulture": {
        "title": "Sliven Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SlivenLandmarks", "label": "Landmarks" },
        "link2": { "href": "SlivenGeography", "label": "Geography" },
    },
    "SlivenGeography": {
        "title": "Sliven Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SlivenLandmarks", "label": "Landmarks" },
        "link2": { "href": "SlivenCulture", "label": "Culture" },
    },
    "HaskovoLandmarks": {
        "title": "Haskovo Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "HaskovoCulture", "label": "Culture" },
        "link2": { "href": "HaskovoGeography", "label": "Geography" },
    },
    "HaskovoCulture": {
        "title": "Haskovo Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "HaskovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "HaskovoGeography", "label": "Geography" },
    },
    "HaskovoGeography": {
        "title": "Haskovo Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "HaskovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "HaskovoCulture", "label": "Culture" },
    },
    "StaraZagoraLandmarks": {
        "title": "Stara Zagora Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Stara ZagoraCulture", "label": "Culture" },
        "link2": { "href": "Stara ZagoraGeography", "label": "Geography" },
    },
    "StaraZagoraCulture": {
        "title": "Stara Zagora Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Stara ZagoraLandmarks", "label": "Landmarks" },
        "link2": { "href": "Stara ZagoraGeography", "label": "Geography" },
    },
    "StaraZagoraGeography": {
        "title": "Stara Zagora Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Stara ZagoraLandmarks", "label": "Landmarks" },
        "link2": { "href": "Stara ZagoraCulture", "label": "Culture" },
    },
    "PazardzhikLandmarks": {
        "title": "Pazardzhik Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PazardzhikCulture", "label": "Culture" },
        "link2": { "href": "PazardzhikGeography", "label": "Geography" },
    },
    "PazardzhikCulture": {
        "title": "Pazardzhik Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PazardzhikLandmarks", "label": "Landmarks" },
        "link2": { "href": "PazardzhikGeography", "label": "Geography" },
    },
    "PazardzhikGeography": {
        "title": "Pazardzhik Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PazardzhikLandmarks", "label": "Landmarks" },
        "link2": { "href": "PazardzhikCulture", "label": "Culture" },
    },
    "PlovdivLandmarks": {
        "title": "Plovdiv Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PlovdivCulture", "label": "Culture" },
        "link2": { "href": "PlovdivGeography", "label": "Geography" },
    },
    "PlovdivCulture": {
        "title": "Plovdiv Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PlovdivLandmarks", "label": "Landmarks" },
        "link2": { "href": "PlovdivGeography", "label": "Geography" },
    },
    "PlovdivGeography": {
        "title": "Plovdiv Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PlovdivLandmarks", "label": "Landmarks" },
        "link2": { "href": "PlovdivCulture", "label": "Culture" },
    },
    "SmolyanLandmarks": {
        "title": "Smolyan Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SmolyanCulture", "label": "Culture" },
        "link2": { "href": "SmolyanGeography", "label": "Geography" },
    },
    "SmolyanCulture": {
        "title": "Smolyan Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SmolyanLandmarks", "label": "Landmarks" },
        "link2": { "href": "SmolyanGeography", "label": "Geography" },
    },
    "SmolyanGeography": {
        "title": "Smolyan Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SmolyanLandmarks", "label": "Landmarks" },
        "link2": { "href": "SmolyanCulture", "label": "Culture" },
    },
    "KardzhaliLandmarks": {
        "title": "Kardzhali Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "KardzhaliCulture", "label": "Culture" },
        "link2": { "href": "KardzhaliGeography", "label": "Geography" },
    },
    "KardzhaliCulture": {
        "title": "Kardzhali Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "KardzhaliLandmarks", "label": "Landmarks" },
        "link2": { "href": "KardzhaliGeography", "label": "Geography" },
    },
    "KardzhaliGeography": {
        "title": "Kardzhali Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "KardzhaliLandmarks", "label": "Landmarks" },
        "link2": { "href": "KardzhaliCulture", "label": "Culture" },
    },
    "SofiaLandmarks": {
        "title": "Sofia Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SofiaCulture", "label": "Culture" },
        "link2": { "href": "SofiaGeography", "label": "Geography" },
    },
    "SofiaCulture": {
        "title": "Sofia Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SofiaLandmarks", "label": "Landmarks" },
        "link2": { "href": "SofiaGeography", "label": "Geography" },
    },
    "SofiaGeography": {
        "title": "Sofia Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SofiaLandmarks", "label": "Landmarks" },
        "link2": { "href": "SofiaCulture", "label": "Culture" },
    },
    "SofiaRegionLandmarks": {
        "title": "Sofia Region Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Sofia RegionCulture", "label": "Culture" },
        "link2": { "href": "Sofia RegionGeography", "label": "Geography" },
    },
    "SofiaRegionCulture": {
        "title": "Sofia Region Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Sofia RegionLandmarks", "label": "Landmarks" },
        "link2": { "href": "Sofia RegionGeography", "label": "Geography" },
    },
    "SofiaRegionGeography": {
        "title": "Sofia Region Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Sofia RegionLandmarks", "label": "Landmarks" },
        "link2": { "href": "Sofia RegionCulture", "label": "Culture" },
    },
    "PernikLandmarks": {
        "title": "Pernik Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PernikCulture", "label": "Culture" },
        "link2": { "href": "PernikGeography", "label": "Geography" },
    },
    "PernikCulture": {
        "title": "Pernik Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PernikLandmarks", "label": "Landmarks" },
        "link2": { "href": "PernikGeography", "label": "Geography" },
    },
    "PernikGeography": {
        "title": "Pernik Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PernikLandmarks", "label": "Landmarks" },
        "link2": { "href": "PernikCulture", "label": "Culture" },
    },
    "GabrovoLandmarks": {
        "title": "Gabrovo Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "GabrovoCulture", "label": "Culture" },
        "link2": { "href": "GabrovoGeography", "label": "Geography" },
    },
    "GabrovoCulture": {
        "title": "Gabrovo Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "GabrovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "GabrovoGeography", "label": "Geography" },
    },
    "GabrovoGeography": {
        "title": "Gabrovo Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "GabrovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "GabrovoCulture", "label": "Culture" },
    },
    "LovechLandmarks": {
        "title": "Lovech Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "LovechCulture", "label": "Culture" },
        "link2": { "href": "LovechGeography", "label": "Geography" },
    },
    "LovechCulture": {
        "title": "Lovech Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "LovechLandmarks", "label": "Landmarks" },
        "link2": { "href": "LovechGeography", "label": "Geography" },
    },
    "LovechGeography": {
        "title": "Lovech Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "LovechLandmarks", "label": "Landmarks" },
        "link2": { "href": "LovechCulture", "label": "Culture" },
    },
    "PlevenLandmarks": {
        "title": "Pleven Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PlevenCulture", "label": "Culture" },
        "link2": { "href": "PlevenGeography", "label": "Geography" },
    },
    "PlevenCulture": {
        "title": "Pleven Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PlevenLandmarks", "label": "Landmarks" },
        "link2": { "href": "PlevenGeography", "label": "Geography" },
    },
    "PlevenGeography": {
        "title": "Pleven Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "PlevenLandmarks", "label": "Landmarks" },
        "link2": { "href": "PlevenCulture", "label": "Culture" },
    },
    "VelikoTarnovoLandmarks": {
        "title": "Veliko Tarnovo Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Veliko TarnovoCulture", "label": "Culture" },
        "link2": { "href": "Veliko TarnovoGeography", "label": "Geography" },
    },
    "VelikoTarnovoCulture": {
        "title": "Veliko Tarnovo Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Veliko TarnovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "Veliko TarnovoGeography", "label": "Geography" },
    },
    "VelikoTarnovoGeography": {
        "title": "Veliko Tarnovo Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "Veliko TarnovoLandmarks", "label": "Landmarks" },
        "link2": { "href": "Veliko TarnovoCulture", "label": "Culture" },
    },
    "MontanaLandmarks": {
        "title": "Montana Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "MontanaCulture", "label": "Culture" },
        "link2": { "href": "MontanaGeography", "label": "Geography" },
    },
    "MontanaCulture": {
        "title": "Montana Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "MontanaLandmarks", "label": "Landmarks" },
        "link2": { "href": "MontanaGeography", "label": "Geography" },
    },
    "MontanaGeography": {
        "title": "Montana Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "MontanaLandmarks", "label": "Landmarks" },
        "link2": { "href": "MontanaCulture", "label": "Culture" },
    },
    "VracaLandmarks": {
        "title": "Vraca Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VracaCulture", "label": "Culture" },
        "link2": { "href": "VracaGeography", "label": "Geography" },
    },
    "VracaCulture": {
        "title": "Vraca Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VracaLandmarks", "label": "Landmarks" },
        "link2": { "href": "VracaGeography", "label": "Geography" },
    },
    "VracaGeography": {
        "title": "Vraca Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VracaLandmarks", "label": "Landmarks" },
        "link2": { "href": "VracaCulture", "label": "Culture" },
    },
    "KyustendilLandmarks": {
        "title": "Kyustendil Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "KyustendilCulture", "label": "Culture" },
        "link2": { "href": "KyustendilGeography", "label": "Geography" },
    },
    "KyustendilCulture": {
        "title": "Kyustendil Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "KyustendilLandmarks", "label": "Landmarks" },
        "link2": { "href": "KyustendilGeography", "label": "Geography" },
    },
    "KyustendilGeography": {
        "title": "Kyustendil Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "KyustendilLandmarks", "label": "Landmarks" },
        "link2": { "href": "KyustendilCulture", "label": "Culture" },
    },
    "VidinLandmarks": {
        "title": "Vidin Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VidinCulture", "label": "Culture" },
        "link2": { "href": "VidinGeography", "label": "Geography" },
    },
    "VidinCulture": {
        "title": "Vidin Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VidinLandmarks", "label": "Landmarks" },
        "link2": { "href": "VidinGeography", "label": "Geography" },
    },
    "VidinGeography": {
        "title": "Vidin Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VidinLandmarks", "label": "Landmarks" },
        "link2": { "href": "VidinCulture", "label": "Culture" },
    },
    "BurgasLandmarks": {
        "title": "Burgas Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "BurgasCulture", "label": "Culture" },
        "link2": { "href": "BurgasGeography", "label": "Geography" },
    },
    "BurgasCulture": {
        "title": "Burgas Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "BurgasLandmarks", "label": "Landmarks" },
        "link2": { "href": "BurgasGeography", "label": "Geography" },
    },
    "BurgasGeography": {
        "title": "Burgas Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "BurgasLandmarks", "label": "Landmarks" },
        "link2": { "href": "BurgasCulture", "label": "Culture" },
    },
    "YambolLandmarks": {
        "title": "Yambol Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "YambolCulture", "label": "Culture" },
        "link2": { "href": "YambolGeography", "label": "Geography" },
    },
    "YambolCulture": {
        "title": "Yambol Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "YambolLandmarks", "label": "Landmarks" },
        "link2": { "href": "YambolGeography", "label": "Geography" },
    },
    "YambolGeography": {
        "title": "Yambol Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "YambolLandmarks", "label": "Landmarks" },
        "link2": { "href": "YambolCulture", "label": "Culture" },
    },
    "RazgradLandmarks": {
        "title": "Razgrad Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "RazgradCulture", "label": "Culture" },
        "link2": { "href": "RazgradGeography", "label": "Geography" },
    },
    "RazgradCulture": {
        "title": "Razgrad Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "RazgradLandmarks", "label": "Landmarks" },
        "link2": { "href": "RazgradGeography", "label": "Geography" },
    },
    "RazgradGeography": {
        "title": "Razgrad Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "RazgradLandmarks", "label": "Landmarks" },
        "link2": { "href": "RazgradCulture", "label": "Culture" },
    },
    "TargovishteLandmarks": {
        "title": "Targovishte Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "TargovishteCulture", "label": "Culture" },
        "link2": { "href": "TargovishteGeography", "label": "Geography" },
    },
    "TargovishteCulture": {
        "title": "Targovishte Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "TargovishteLandmarks", "label": "Landmarks" },
        "link2": { "href": "TargovishteGeography", "label": "Geography" },
    },
    "TargovishteGeography": {
        "title": "Targovishte Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "TargovishteLandmarks", "label": "Landmarks" },
        "link2": { "href": "TargovishteCulture", "label": "Culture" },
    },
    "ShumenLandmarks": {
        "title": "Shumen Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "ShumenCulture", "label": "Culture" },
        "link2": { "href": "ShumenGeography", "label": "Geography" },
    },
    "ShumenCulture": {
        "title": "Shumen Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "ShumenLandmarks", "label": "Landmarks" },
        "link2": { "href": "ShumenGeography", "label": "Geography" },
    },
    "ShumenGeography": {
        "title": "Shumen Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "ShumenLandmarks", "label": "Landmarks" },
        "link2": { "href": "ShumenCulture", "label": "Culture" },
    },
    "DobrichLandmarks": {
        "title": "Dobrich Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "DobrichCulture", "label": "Culture" },
        "link2": { "href": "DobrichGeography", "label": "Geography" },
    },
    "DobrichCulture": {
        "title": "Dobrich Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "DobrichLandmarks", "label": "Landmarks" },
        "link2": { "href": "DobrichGeography", "label": "Geography" },
    },
    "DobrichGeography": {
        "title": "Dobrich Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "DobrichLandmarks", "label": "Landmarks" },
        "link2": { "href": "DobrichCulture", "label": "Culture" },
    },
    "VarnaLandmarks": {
        "title": "Varna Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VarnaCulture", "label": "Culture" },
        "link2": { "href": "VarnaGeography", "label": "Geography" },
    },
    "VarnaCulture": {
        "title": "Varna Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VarnaLandmarks", "label": "Landmarks" },
        "link2": { "href": "VarnaGeography", "label": "Geography" },
    },
    "VarnaGeography": {
        "title": "Varna Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "VarnaLandmarks", "label": "Landmarks" },
        "link2": { "href": "VarnaCulture", "label": "Culture" },
    },
    "SilistraLandmarks": {
        "title": "Silistra Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SilistraCulture", "label": "Culture" },
        "link2": { "href": "SilistraGeography", "label": "Geography" },
    },
    "SilistraCulture": {
        "title": "Silistra Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SilistraLandmarks", "label": "Landmarks" },
        "link2": { "href": "SilistraGeography", "label": "Geography" },
    },
    "SilistraGeography": {
        "title": "Silistra Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "SilistraLandmarks", "label": "Landmarks" },
        "link2": { "href": "SilistraCulture", "label": "Culture" },
    },
    "RuseLandmarks": {
        "title": "Ruse Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "RuseCulture", "label": "Culture" },
        "link2": { "href": "RuseGeography", "label": "Geography" },
    },
    "RuseCulture": {
        "title": "Ruse Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "RuseLandmarks", "label": "Landmarks" },
        "link2": { "href": "RuseGeography", "label": "Geography" },
    },
    "RuseGeography": {
        "title": "Ruse Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "RuseLandmarks", "label": "Landmarks" },
        "link2": { "href": "RuseCulture", "label": "Culture" },
    },
    "BlagoevgradLandmarks": {
        "title": "Blagoevgrad Landmarks",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "BlagoevgradCulture", "label": "Culture" },
        "link2": { "href": "BlagoevgradGeography", "label": "Geography" },
    },
    "BlagoevgradCulture": {
        "title": "Blagoevgrad Culture",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "BlagoevgradLandmarks", "label": "Landmarks" },
        "link2": { "href": "BlagoevgradGeography", "label": "Geography" },
    },
    "BlagoevgradGeography": {
        "title": "Blagoevgrad Geography",
        "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe voluptatum sunt minus voluptatem quaerat quod earum tenetur officia quis.",
        "link1": { "href": "BlagoevgradLandmarks", "label": "Landmarks" },
        "link2": { "href": "BlagoevgradCulture", "label": "Culture" },
    },
};